import type { ElementDefinition, WireType } from '../types/index.ts';

export const WIRE_COLORS: Record<WireType, string> = {
  L1: '#808080',
  L2: '#1a1a1a',
  L3: '#8B4513',
  N:  '#0000CD',
  PE: '#228B22',
  DC: '#FF0000',
};

export const ELEMENT_DEFINITIONS: ElementDefinition[] = [
  {
    id: 'inverter',
    name: 'Falownik DC/AC',
    category: 'inverter',
    designation: 'U',
    nodeType: 'inverter',
    defaultLabel: 'U1',
    parameters: [
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'power', label: 'Moc', type: 'number', unit: 'kW' },
      { key: 'mppt', label: 'Liczba MPPT', type: 'number', defaultValue: 2 },
      { key: 'type', label: 'Typ', type: 'select', options: ['ON-grid', 'Hybryda', 'Off-grid'] },
    ],
  },
  {
    id: 'hybrid_inverter',
    name: 'Falownik hybrydowy',
    category: 'inverter',
    designation: 'U',
    nodeType: 'hybridInverter',
    defaultLabel: 'U1',
    parameters: [
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'power', label: 'Moc', type: 'number', unit: 'kW' },
      { key: 'mppt', label: 'Liczba MPPT', type: 'number', defaultValue: 2 },
    ],
  },
  {
    id: 'battery',
    name: 'Magazyn energii',
    category: 'inverter',
    designation: 'G',
    nodeType: 'battery',
    defaultLabel: 'BAT',
    parameters: [
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'capacity', label: 'Pojemność', type: 'number', unit: 'kWh' },
      { key: 'voltage', label: 'Napięcie', type: 'number', unit: 'V' },
    ],
  },
  {
    id: 'rcd',
    name: 'Wyłącznik RCD',
    category: 'ac',
    designation: 'F-RCD',
    nodeType: 'rcd',
    defaultLabel: 'F1',
    parameters: [
      { key: 'rcdType', label: 'Typ', type: 'select', options: ['A', 'B', 'F', 'B+'] },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 25 },
      { key: 'sensitivityCurrent', label: 'IΔn', type: 'number', unit: 'mA', defaultValue: 30 },
      { key: 'poles', label: 'Bieguny', type: 'select', options: ['2P', '4P'] },
    ],
  },
  {
    id: 'mcb_3p',
    name: 'Wyłącznik MCB 3P',
    category: 'ac',
    designation: 'F',
    nodeType: 'mcb',
    defaultLabel: 'F2',
    parameters: [
      { key: 'curve', label: 'Krzywa', type: 'select', options: ['B', 'C', 'D'] },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 16 },
      { key: 'poles', label: 'Bieguny', type: 'select', options: ['1P', '2P', '3P', '4P'], defaultValue: '3P' },
    ],
  },
  {
    id: 'mcb_1p',
    name: 'Wyłącznik MCB 1P',
    category: 'ac',
    designation: 'F',
    nodeType: 'mcb',
    defaultLabel: 'F3',
    parameters: [
      { key: 'curve', label: 'Krzywa', type: 'select', options: ['B', 'C', 'D'] },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 16 },
      { key: 'poles', label: 'Bieguny', type: 'select', options: ['1P', '2P', '3P', '4P'], defaultValue: '1P' },
    ],
  },
  {
    id: 'ac_busbar',
    name: 'Szyna zbiorcza AC',
    category: 'wiring',
    designation: '',
    nodeType: 'acBusbar',
    defaultLabel: 'Szyna AC',
    parameters: [],
  },
  {
    id: 'ground_rod',
    name: 'Uziom',
    category: 'grounding',
    designation: '',
    nodeType: 'ground',
    defaultLabel: 'Uziom',
    parameters: [
      { key: 'resistance', label: 'RE', type: 'number', unit: 'Ω' },
      { key: 'groundType', label: 'Typ', type: 'select', options: ['pionowy', 'poziomy'] },
    ],
  },
  // --- Rozdzielnice (prostokat kreskowany z tytulem) ---
  {
    id: 'main_enclosure',
    name: 'Rozdzielnica główna',
    category: 'enclosure',
    designation: 'RG',
    nodeType: 'enclosure',
    defaultLabel: 'RG',
    parameters: [],
  },
  {
    id: 'sub_enclosure',
    name: 'Podrozdzielnica',
    category: 'enclosure',
    designation: 'RP',
    nodeType: 'enclosure',
    defaultLabel: 'RP',
    parameters: [],
  },
  {
    id: 'black_box',
    name: 'Rozdzielnica (uproszczona)',
    category: 'enclosure',
    designation: '',
    nodeType: 'blackBox',
    defaultLabel: 'RG',
    parameters: [
      { key: 'fontSize', label: 'Rozmiar czcionki', type: 'number', defaultValue: 12 },
    ],
  },
  {
    id: 'pv_dc_enclosure',
    name: 'Rozdzielnica DC PV',
    category: 'enclosure',
    designation: 'RPV-DC',
    nodeType: 'enclosure',
    defaultLabel: 'RPV-DC',
    parameters: [],
  },
  {
    id: 'pv_ac_enclosure',
    name: 'Rozdzielnica AC PV',
    category: 'enclosure',
    designation: 'RPV-AC',
    nodeType: 'enclosure',
    defaultLabel: 'RPV-AC',
    parameters: [],
  },
  // --- Strona DC (Etap 5) ---
  {
    id: 'pv_string',
    name: 'String PV',
    category: 'dc',
    designation: 'PV',
    nodeType: 'pvString',
    defaultLabel: 'PV1',
    parameters: [
      { key: 'panelCount', label: 'Liczba paneli', type: 'number' },
      { key: 'model', label: 'Model panelu', type: 'text' },
      { key: 'vString', label: 'Vstring', type: 'number', unit: 'V' },
      { key: 'pString', label: 'Pstring', type: 'number', unit: 'W' },
    ],
  },
  {
    id: 'spd_dc',
    name: 'SPD DC',
    category: 'dc',
    designation: 'F-SPD',
    nodeType: 'spdDc',
    defaultLabel: 'SPD-DC',
    parameters: [
      { key: 'spdType', label: 'Typ', type: 'select', options: ['T1', 'T2', 'T1+2'] },
      { key: 'uc', label: 'UC', type: 'number', unit: 'V' },
      { key: 'in', label: 'In', type: 'number', unit: 'kA' },
      { key: 'imax', label: 'Imax', type: 'number', unit: 'kA' },
    ],
  },
  {
    id: 'dc_disconnect',
    name: 'Rozłącznik DC',
    category: 'dc',
    designation: 'QS',
    nodeType: 'dcDisconnect',
    defaultLabel: 'QS1',
    parameters: [
      { key: 'voltage', label: 'Un', type: 'number', unit: 'V DC' },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A' },
    ],
  },
  {
    id: 'fuse_gpv',
    name: 'Bezpiecznik gPV',
    category: 'dc',
    designation: 'F',
    nodeType: 'fuseGpv',
    defaultLabel: 'F-PV',
    parameters: [
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 15 },
      { key: 'voltage', label: 'Un', type: 'number', unit: 'V DC', defaultValue: 1000 },
    ],
  },
  // --- Dodatkowe AC (Etap 5) ---
  {
    id: 'rcbo',
    name: 'RCBO (RCD+MCB)',
    category: 'ac',
    designation: 'F',
    nodeType: 'rcbo',
    defaultLabel: 'F3',
    parameters: [
      { key: 'curve', label: 'Krzywa', type: 'select', options: ['B', 'C', 'D'] },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 16 },
      { key: 'sensitivityCurrent', label: 'IΔn', type: 'number', unit: 'mA', defaultValue: 30 },
      { key: 'rcdType', label: 'Typ RCD', type: 'select', options: ['A', 'B', 'F', 'B+'] },
    ],
  },
  {
    id: 'spd_ac',
    name: 'SPD AC',
    category: 'ac',
    designation: 'F-SPD',
    nodeType: 'spdAc',
    defaultLabel: 'SPD-AC',
    parameters: [
      { key: 'spdType', label: 'Typ', type: 'select', options: ['T1', 'T2', 'T3', 'T1+2'] },
      { key: 'config', label: 'Konfiguracja', type: 'select', options: ['3+1', '4+0'] },
      { key: 'uc', label: 'UC', type: 'number', unit: 'V' },
    ],
  },
  {
    id: 'meter',
    name: 'Licznik kWh',
    category: 'ac',
    designation: 'P',
    nodeType: 'meter',
    defaultLabel: 'P1',
    parameters: [
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'meterType', label: 'Typ', type: 'select', options: ['1-fazowy', '3-fazowy'] },
      { key: 'bidirectional', label: 'Dwukierunkowy', type: 'select', options: ['Tak', 'Nie'] },
    ],
  },
  {
    id: 'main_switch',
    name: 'Wyłącznik główny',
    category: 'ac',
    designation: 'Q',
    nodeType: 'mainSwitch',
    defaultLabel: 'Q1',
    parameters: [
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 63 },
      { key: 'poles', label: 'Bieguny', type: 'select', options: ['1P', '2P', '3P', '4P'] },
    ],
  },
  {
    id: 'ac_disconnect',
    name: 'Rozłącznik AC',
    category: 'ac',
    designation: 'QS',
    nodeType: 'mainSwitch',
    defaultLabel: 'QS1',
    parameters: [
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A' },
      { key: 'poles', label: 'Bieguny', type: 'select', options: ['1P', '2P', '3P', '4P'] },
    ],
  },
  {
    id: 'fire_button',
    name: 'Przycisk PPOŻ',
    category: 'ac',
    designation: 'S-PPOZ',
    nodeType: 'fireButton',
    defaultLabel: 'PPOŻ',
    parameters: [],
  },
  {
    id: 'socket_32a',
    name: 'Gniazdo 32A 3f+N+PE',
    category: 'ac',
    designation: 'X',
    nodeType: 'socket32',
    defaultLabel: 'X1',
    parameters: [
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 32 },
    ],
  },
  {
    id: 'zug_n',
    name: 'ZUG N',
    category: 'ac',
    designation: '',
    nodeType: 'zugN',
    defaultLabel: 'N',
    parameters: [],
  },
  {
    id: 'zug_l1',
    name: 'ZUG L1',
    category: 'ac',
    designation: '',
    nodeType: 'zugL1',
    defaultLabel: 'L1',
    parameters: [],
  },
  {
    id: 'zug_l2',
    name: 'ZUG L2',
    category: 'ac',
    designation: '',
    nodeType: 'zugL2',
    defaultLabel: 'L2',
    parameters: [],
  },
  {
    id: 'zug_l3',
    name: 'ZUG L3',
    category: 'ac',
    designation: '',
    nodeType: 'zugL3',
    defaultLabel: 'L3',
    parameters: [],
  },
  {
    id: 'ct_l1',
    name: 'Przekładnik CT L1',
    category: 'ac',
    designation: 'TA',
    nodeType: 'ct',
    defaultLabel: 'TA1',
    parameters: [
      { key: 'ratio', label: 'Przekładnia', type: 'text', defaultValue: '100/5A' },
      { key: 'color', label: 'Kolor fazy', type: 'select', options: ['#808080', '#1a1a1a', '#8B4513'], defaultValue: '#808080' },
    ],
  },
  {
    id: 'ct_l2',
    name: 'Przekładnik CT L2',
    category: 'ac',
    designation: 'TA',
    nodeType: 'ct',
    defaultLabel: 'TA2',
    parameters: [
      { key: 'ratio', label: 'Przekładnia', type: 'text', defaultValue: '100/5A' },
      { key: 'color', label: 'Kolor fazy', type: 'select', options: ['#808080', '#1a1a1a', '#8B4513'], defaultValue: '#1a1a1a' },
    ],
  },
  {
    id: 'ct_l3',
    name: 'Przekładnik CT L3',
    category: 'ac',
    designation: 'TA',
    nodeType: 'ct',
    defaultLabel: 'TA3',
    parameters: [
      { key: 'ratio', label: 'Przekładnia', type: 'text', defaultValue: '100/5A' },
      { key: 'color', label: 'Kolor fazy', type: 'select', options: ['#808080', '#1a1a1a', '#8B4513'], defaultValue: '#8B4513' },
    ],
  },
  {
    id: 'zug_2n',
    name: 'ZUG-2 N',
    category: 'ac',
    designation: '',
    nodeType: 'zug2N',
    defaultLabel: 'N',
    parameters: [],
  },
  {
    id: 'smart_meter',
    name: 'Smart Meter (Pstryk)',
    category: 'ac',
    designation: 'SM',
    nodeType: 'smartMeter',
    defaultLabel: 'SM',
    parameters: [
      { key: 'model', label: 'Model', type: 'text', defaultValue: 'Pstryk' },
    ],
  },
  {
    id: 'phase_monitor',
    name: 'Kontrolka faz',
    category: 'ac',
    designation: '',
    nodeType: 'phaseMonitor',
    defaultLabel: 'KF',
    parameters: [],
  },
  {
    id: 'meter_osd',
    name: 'Licznik OSD kWh',
    category: 'ac',
    designation: 'P',
    nodeType: 'meterOsd',
    defaultLabel: 'kWh',
    parameters: [],
  },
  {
    id: 'wire_point_l1',
    name: 'Punkt L1',
    category: 'wiring',
    designation: '',
    nodeType: 'wirePoint',
    defaultLabel: '',
    parameters: [
      { key: 'wireType', label: 'Żyła', type: 'select', options: ['L1', 'L2', 'L3', 'N', 'PE'], defaultValue: 'L1' },
    ],
  },
  {
    id: 'wire_point_l2',
    name: 'Punkt L2',
    category: 'wiring',
    designation: '',
    nodeType: 'wirePoint',
    defaultLabel: '',
    parameters: [
      { key: 'wireType', label: 'Żyła', type: 'select', options: ['L1', 'L2', 'L3', 'N', 'PE'], defaultValue: 'L2' },
    ],
  },
  {
    id: 'wire_point_l3',
    name: 'Punkt L3',
    category: 'wiring',
    designation: '',
    nodeType: 'wirePoint',
    defaultLabel: '',
    parameters: [
      { key: 'wireType', label: 'Żyła', type: 'select', options: ['L1', 'L2', 'L3', 'N', 'PE'], defaultValue: 'L3' },
    ],
  },
  {
    id: 'wire_point_n',
    name: 'Punkt N',
    category: 'wiring',
    designation: '',
    nodeType: 'wirePoint',
    defaultLabel: '',
    parameters: [
      { key: 'wireType', label: 'Żyła', type: 'select', options: ['L1', 'L2', 'L3', 'N', 'PE'], defaultValue: 'N' },
    ],
  },
  {
    id: 'wire_point_pe',
    name: 'Punkt PE',
    category: 'wiring',
    designation: '',
    nodeType: 'wirePoint',
    defaultLabel: '',
    parameters: [
      { key: 'wireType', label: 'Żyła', type: 'select', options: ['L1', 'L2', 'L3', 'N', 'PE'], defaultValue: 'PE' },
    ],
  },
  {
    id: 'single_line_mcb',
    name: 'Zabezpieczenie jednokreskowe',
    category: 'ac',
    designation: 'F',
    nodeType: 'singleLineMcb',
    defaultLabel: 'F',
    parameters: [
      { key: 'curve', label: 'Krzywa', type: 'select', options: ['B', 'C', 'D'] },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 25 },
      { key: 'orientation', label: 'Orientacja', type: 'select', options: ['pionowa', 'pozioma'], defaultValue: 'pionowa' },
    ],
  },
  {
    id: 'isolator_3pn',
    name: 'Rozłącznik izolacyjny 3P+N',
    category: 'ac',
    designation: 'QS',
    nodeType: 'isolator',
    defaultLabel: 'QS',
    parameters: [
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 63 },
    ],
  },
  {
    id: 'junction_point',
    name: 'Punkt połączeniowy',
    category: 'wiring',
    designation: '',
    nodeType: 'junctionPoint',
    defaultLabel: '',
    parameters: [],
  },
  {
    id: 'dist_block',
    name: 'Blok rozdzielczy 4P',
    category: 'ac',
    designation: 'BR',
    nodeType: 'distBlock',
    defaultLabel: 'BR1',
    parameters: [
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 125 },
    ],
  },
  {
    id: 'text_label',
    name: 'Opis / etykieta',
    category: 'wiring',
    designation: '',
    nodeType: 'textLabel',
    defaultLabel: 'Opis przewodu',
    parameters: [
      { key: 'fontSize', label: 'Rozmiar czcionki', type: 'number', defaultValue: 11 },
      { key: 'color', label: 'Kolor', type: 'select', options: ['#333', '#FF0000', '#0000CD', '#228B22', '#808080', '#8B4513'], defaultValue: '#333' },
    ],
  },
  {
    id: 'contactor',
    name: 'Stycznik',
    category: 'ac',
    designation: 'KM',
    nodeType: 'contactor',
    defaultLabel: 'KM1',
    parameters: [
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A' },
      { key: 'coilVoltage', label: 'Cewka', type: 'number', unit: 'V' },
    ],
  },
  // --- Uziemienie (Etap 5) ---
  {
    id: 'pe_busbar',
    name: 'Szyna PE',
    category: 'grounding',
    designation: 'PE',
    nodeType: 'busbar',
    defaultLabel: 'PE',
    parameters: [
      { key: 'busbarType', label: 'Typ', type: 'select', options: ['PE', 'PEN', 'N'], defaultValue: 'PE' },
    ],
  },
  {
    id: 'n_busbar',
    name: 'Szyna N',
    category: 'grounding',
    designation: 'N',
    nodeType: 'busbar',
    defaultLabel: 'N',
    parameters: [
      { key: 'busbarType', label: 'Typ', type: 'select', options: ['PE', 'PEN', 'N'], defaultValue: 'N' },
    ],
  },
  // --- Ładowarki EV (Etap 5) ---
  {
    id: 'ev_charger',
    name: 'Ładowarka EV',
    category: 'ev',
    designation: '',
    nodeType: 'evCharger',
    defaultLabel: 'EV1',
    parameters: [
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'power', label: 'Moc', type: 'number', unit: 'kW' },
      { key: 'evType', label: 'Typ', type: 'select', options: ['1-fazowy', '3-fazowy'] },
    ],
  },
  {
    id: 'ev_rcd',
    name: 'RCD typ B (EV)',
    category: 'ev',
    designation: 'F-RCD',
    nodeType: 'rcd',
    defaultLabel: 'F-EV',
    parameters: [
      { key: 'rcdType', label: 'Typ', type: 'select', options: ['B', 'B+'], defaultValue: 'B' },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 40 },
      { key: 'sensitivityCurrent', label: 'IΔn', type: 'number', unit: 'mA', defaultValue: 30 },
      { key: 'poles', label: 'Bieguny', type: 'select', options: ['2P', '4P'] },
    ],
  },
  // --- Przełączniki zasilania (Etap 5) ---
  {
    id: 'transfer_switch',
    name: 'Przełącznik I-0-II',
    category: 'transfer',
    designation: 'Q',
    nodeType: 'transferSwitch',
    defaultLabel: 'Q-SZR',
    parameters: [
      { key: 'model', label: 'Model', type: 'text', defaultValue: 'SFT440' },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A', defaultValue: 40 },
    ],
  },
  {
    id: 'ats',
    name: 'ATS (auto)',
    category: 'transfer',
    designation: 'QA',
    nodeType: 'transferSwitch',
    defaultLabel: 'ATS',
    parameters: [
      { key: 'switchType', label: 'Typ', type: 'select', options: ['automatyczny'], defaultValue: 'automatyczny' },
      { key: 'ratingCurrent', label: 'In', type: 'number', unit: 'A' },
      { key: 'switchTime', label: 'Czas przełączenia', type: 'number', unit: 'ms' },
    ],
  },
];
